Active Directory ist ein Produkt von Microsoft, das IT-Administratoren beim Verwalten und Absichern von Benutzerkonten, Systemen und weiteren Ressourcen in ihrem Unternehmensnetzwerk unterstützt. Es kann unter anderem als Identity Provider (IdP) dienen und bildet einen Single Point of Access zu verschiedenen Ressourcen, die über Ihr Unternehmensnetzwerk erreichbar sind. In der Praxis lässt sich Active Directory am besten als eine Datenbank beschreiben, in der alle Benutzer, Gruppen und Rechner Ihrer Organisation erfasst sind. Active Directory ermöglicht damit den Zugriff auf Daten, Anwendungen, IT-Systeme und Peripheriegeräte. Eine wichtige Aufgabe, denn dieser Zugang ist für Mitarbeitende notwendig, um ihre täglichen Tätigkeiten auszuführen. Dies erfordert eine sorgfältige Verwaltung sowohl der Benutzer als auch der Berechtigungen in Active Directory.

Das Koppeln einer On-Premises-Active-Directory-Umgebung mit Ihrer cloudbasierten Office-Anwendungslandschaft klingt nach einer grundlegenden Funktionalität, ist in der Praxis jedoch nicht trivial. Der IdP läuft On-Premises, während viele der zu integrierenden Anwendungen in der Cloud gehostet werden. Daher ist ein spezieller Agent erforderlich, der Ihre On-Premises-Umgebung nahtlos mit Ihren Cloud-Anwendungen verbindet, wobei Sicherheit, Verlässlichkeit und Robustheit unverzichtbar sind. Im Gegensatz zu vielen konkurrierenden IAM-Lösungen kann HelloID Ihre On-Premises-Active-Directory-Implementierung problemlos mit Ihren Cloud-Anwendungen koppeln.

## Wie HelloID mit Active Directory integriert

Die Identity- und Access-Management-Lösung (IAM-Lösung) HelloID verfügt über eine Standardanbindung an Active Directory. HelloID automatisiert sämtliche Verwaltungsprozesse rund um Benutzerkonten und Zugriffsrechte in Active Directory. Grundlage sind Informationen aus Ihrem HR- und Planungssystem. Sie müssen sich somit nicht mehr um die Verwaltung von Benutzern und Berechtigungen in Active Directory kümmern und arbeiten nachweislich effizient, sicher und compliant.

Im Folgenden ein Auszug der Möglichkeiten, die HelloID bietet:

**Erstellen neuer und Verwalten bestehender Benutzerkonten**  
Die Belegschaft jedes Unternehmens unterliegt Veränderungen. Fügen Sie einen neuen Benutzer in Ihrem HR-System hinzu oder entfernen Sie ihn, überträgt HelloID dank der Anbindung an dieses Quellsystem diese Informationen automatisch nach Active Directory. Praktisch, denn so stellen Sie sicher, dass alle Informationen im IdP vollständig aktuell sind und den Daten in Ihrem HR-System entsprechen. Vorteilhaft ist, dass Sie Konten nicht neu anlegen müssen, denn HelloID kann bestehende Konten für Sie korrelieren. Sie verfügen bereits über eine produktive Umgebung, und HelloID übernimmt die Steuerung im laufenden Betrieb, ohne Unterbrechungen. In den meisten Fällen möchten Sie bestehende Konten beibehalten. Sie bestimmen, ob HelloID bestehende Konten bereinigen darf oder ob Sie eine Baseline setzen und HelloID nur neu angelegte Konten verwalten lassen. Ein wichtiger Aspekt, denn je älter Konten sind, desto eher laufen manuell gepflegte Felder auseinander. Zum Beispiel, weil Mitarbeitende in neue Funktionen wechseln oder sich die Stellenstruktur ändert. HelloID kann diese Informationen für Sie bereinigen.

**Benutzer anlegen, aktivieren, deaktivieren und löschen**  
Dank HelloID müssen Sie sich nicht um das Anlegen, Aktivieren und Deaktivieren von Benutzerkonten kümmern. HelloID kann zudem automatisiert Konten aus Active Directory löschen. Wichtig ist dabei, dass HelloID ausschließlich das Benutzerobjekt entfernt und nicht die zugehörigen Ressourcen. So kann einem Konto beispielsweise ein Homeverzeichnis zugeordnet sein. Da HelloID nicht Eigentümer dieser Daten ist, darf die IAM-Lösung diese Informationen gesetzlich nicht löschen. Indem HelloID diese Daten unberührt lässt, erhalten Sie Sicherheit in Bezug auf Ihre Compliance mit relevanten Gesetzen und Vorschriften und behalten die vollständige Kontrolle über Ihre Daten.

**Den richtigen Benutzernamen zuweisen**  
Ein wichtiger Punkt beim Anlegen eines Benutzerkontos ist die Wahl des richtigen Benutzernamens. Entscheiden Sie zum Beispiel, ob die vollständigen Vor- und Nachnamen in einer E-Mail-Adresse enthalten sein sollen oder ob Sie eine Kombination aus Initialen oder Nachnamen wählen. Wie gehen Sie zudem mit drohenden Dubletten bei Benutzernamen um. Dank Namenskonventionen in HelloID standardisieren Sie diesen Prozess und stellen sicher, dass Benutzernamen stets konsistent aufgebaut sind.

**Gruppenmitgliedschaften zuweisen oder entziehen**  
Ein zentrales Thema bei der Benutzerverwaltung in Ihrer Organisation ist das Management der Gruppenmitgliedschaften. Über Gruppenmitgliedschaften können Sie Berechtigungen einfach korrekt zuweisen. Charakteristisch ist, dass Sie Berechtigungen einmal für eine Gruppe definieren und anschließend Benutzer dieser Gruppe zuordnen. Dank der Integration von HelloID mit Active Directory müssen Sie sich um diesen Prozess nicht kümmern und stellen sicher, dass Benutzer die richtigen Gruppenmitgliedschaften erhalten und diese bei Bedarf rechtzeitig entzogen werden. Wichtig ist auch, dass HelloID Gruppen automatisiert für Sie anlegen kann. Zum Beispiel, wenn die HR-Abteilung im HR-System eine neue Abteilung anlegt. HelloID erkennt in diesem Fall die neue Abteilung und weist darauf basierend die richtigen Mitgliedschaften zu. Dies nennen wir auch Dynamic Permissions. Hinweis: Der Systemadministrator muss in diesem Fall die neu angelegten Gruppen mit den richtigen Ressourcen verknüpfen.

**Attribute anpassen**  
Welche Gruppenmitgliedschaften ein Benutzer benötigt, hängt unter anderem von seiner Funktion ab. Diese Funktion können Sie in hohem Maße automatisiert identifizieren. Dies erfolgt mithilfe von Attributen, die HelloID aus Ihrem Quellsystem abruft. Sie legen selbst fest, anhand welcher Attribute aus dem Quellsystem Sie welche Konten und Rechte in Zielsystemen zuweisen, in diesem Fall Active Directory. Diese Arbeitsweise bietet hohen Komfort. Sie müssen die richtige Funktion eines Benutzers nicht manuell identifizieren, und Sie stellen sicher, dass bei einem Funktionswechsel eines Mitarbeitenden dessen Konten und Rechte durch HelloID bei Bedarf automatisch angepasst werden. Die meisten Quellsysteme kennen eine Konstruktion, bei der ein Mitarbeiter eine oder mehrere Einsätze oder Stellenanteile hat. Effektiv kann ein Mitarbeiter mehrere Funktionen besitzen. Auf Basis aller aktiven Funktionen kann HelloID die korrekten Berechtigungen in Active Directory vergeben.

**Wiederverwendung von E-Mail-Adressen verhindern**  
HelloID kann eine Sperrliste (Blacklist) verwenden, die die Wiederverwendung von E-Mail-Adressen verhindert. Auch wenn ein Benutzerkonto nach der Deaktivierung zu einem späteren Zeitpunkt wieder freigegeben wird und die E-Mail-Adresse technisch gesehen erneut nutzbar wäre, sorgt die Sperrliste dafür, dass diese E-Mail-Adresse niemals erneut vergeben wird. Wichtig, denn so stellen Sie sicher, dass E-Mail-Verkehr nie beim falschen Empfänger landet und dass zum Beispiel Akten, die an eine E-Mail-Adresse geknüpft sind, niemals unbeabsichtigt für Unbefugte zugänglich sind. Die gleiche Vorgehensweise ist übrigens auch auf Benutzernamen anwendbar.

**Organizational Units verwalten**  
In Active Directory arbeiten Sie mit Ordnern, den sogenannten Organisationseinheiten. Verfügt Ihre Organisation zum Beispiel über mehrere Standorte. Dann können Sie eine Ordnerstruktur aufbauen, zwischen diesen Standorten unterscheiden und alle Ordner der zugehörigen Konten im richtigen Standortordner platzieren. HelloID bietet hierfür eine strukturierte Vorgehensweise, die für viel Klarheit sorgt und Missverständnisse vermeidet. So kann HelloID beim Anlegen eines Benutzerkontos automatisch eine Organisationseinheit erstellen, diese bei Aktivierung des Kontos beispielsweise in die richtige Standort-OU verschieben und bei Deaktivierung des Kontos in eine OU verschieben, in der sich deaktivierte Konten befinden.

**Anbindung an Exchange**  
Exchange ist eine Erweiterung von Active Directory, mit der Sie Ihr E-Mail-Verkehr professionell steuern. Die Microsoft-Software sorgt unter anderem dafür, dass Kontakte, Termine und E-Mails auf allen Geräten eines Benutzers verfügbar sind. Grundlage sind Informationen aus Active Directory. HelloID kann sich mit Exchange verbinden, unabhängig davon, ob Ihr Exchange-Server On-Premises oder in der Cloud läuft. Nutzen Sie kein Exchange, wohl aber Exchange Online über Group-based Licensing in Azure. Auch damit kann HelloID umgehen. Wichtig ist der Hinweis, dass Sie dank des HelloID Agents die Exchange-Verwaltungstools nicht benötigen. Der HelloID Agent ist dadurch leichtgewichtig und benötigt weniger Rechte, was im Hinblick auf die Sicherheit wichtig ist.

**Erstellen von Home- und Profilverzeichnissen**  
Für die Datenspeicherung arbeitet Active Directory mit Home- und Profilverzeichnissen. HelloID bietet volle Unterstützung für das Anlegen dieser Verzeichnisse. HelloID kann außerdem sämtliche Berechtigungen, die diesen Verzeichnissen zugeordnet sind, zuverlässig für Sie verwalten. Denken Sie dabei an das Archivieren dieser Verzeichnisse auf derselben Freigabe, zum Beispiel in einem Ordner mit dem Namen Archiv. Es ist auch möglich, den Ordnernamen mit einem Zeitstempel zu versehen.

**Unterstützung für Post-Aktionen**  
HelloID unterstützt sogenannte Post-Aktionen. Dies sind PowerShell-Aktionen, die Administratoren automatisiert ausführen lassen können, nachdem HelloID seine Arbeit erledigt hat. Praktisch, denn als HR-Administrator arbeiten Sie in vielen Fällen mit eigenen Skripten, die Sie ausführen möchten, sobald HelloID fertig ist. Denken Sie dabei an das Hinzufügen eines Textes wie Durch HelloID am [Datum] aktiviert zur Beschreibung eines AD-Kontos nach der Aktivierung durch HelloID. Post-Aktionen sind bei jedem Lifecycle-Event möglich, das HelloID ausführt, wie dem Aktivieren, Deaktivieren oder Löschen eines Kontos.

Besonders an der Kopplung zwischen HelloID und Active Directory ist, dass Sie dank unseres Agents On-Premises-Active-Directory-Konten aus der Cloud heraus verwalten können. HelloID als IDaaS-Lösung hat selbstverständlich keinen direkten Zugriff auf das interne Kundennetzwerk. Alle Aktionen werden über einen speziellen Agent aus HelloID abgerufen und im Netzwerk ausgeführt. Die Kommunikation mit HelloID erfolgt somit stets vom Agent aus und niemals aus der Cloud heraus. Dank unseres Agents entsteht eine nahtlose und vor allem sichere Verbindung zwischen beiden Systemen.

## HelloID für Active Directory hilft Ihnen bei

- **Direkter Zugang zu den richtigen Daten und Anwendungen:** Ihre Mitarbeitenden benötigen Zugriff auf Daten und Unternehmensanwendungen, um ihre Arbeit auszuführen. Dank der Kopplung zwischen HelloID und Active Directory können neue Mitarbeitende an ihrem ersten Tag sofort starten.
- **Erhebliche Zeitersparnis:** Die Verwaltung von Benutzerkonten und Berechtigungen ist komplex und zeitaufwendig, insbesondere wenn die Zahl der Mitarbeitenden in Ihrer Organisation wächst. Die Kopplung von Active Directory mit HelloID automatisiert diesen Prozess in erheblichem Umfang.
- **Reduktion menschlicher Fehler:** Irren ist menschlich, kann jedoch weitreichende Folgen haben. Vergessen Sie zum Beispiel, die Berechtigungen eines ausgeschiedenen Benutzers zu entziehen, kann dies später zu Problemen führen, sowohl in Bezug auf Security als auch Compliance. Mit der Kopplung zwischen Active Directory und HelloID erhalten Sie hier Sicherheit und minimieren das Risiko menschlicher Fehler.
- **Robuste Audits:** Die Einhaltung von Verfahren erfolgt automatisch, wobei alle von HelloID durchgeführten Aktivitäten im Zusammenhang mit Benutzern und Berechtigungen protokolliert werden. Dadurch haben Sie stets den vollständigen Überblick und erfüllen alle Compliance-Anforderungen.

## Active Directory über HelloID mit Quell- und Zielsystemen koppeln

Mithilfe von HelloID können Sie Active Directory mit unterschiedlichsten anderen Systemen koppeln. Die Integrationen erhöhen die Effizienz, mit der Sie Benutzerkonten und Zugriffsrechte verwalten. So schaffen Sie eine sichere und compliant Umgebung, in der Ihre Mitarbeitenden optimal produktiv sind. Einige Beispiele häufiger Integrationen sind:

- **Visma Raet - Active Directory Kopplung:** Eine beliebte HR-Lösung ist Visma Raet. Dank der Visma Raet – Active Directory Kopplung, die Sie mit HelloID einrichten können, überführt die IAM-Lösung automatisch alle relevanten Informationen aus diesem HR-System in Benutzerkonten und Zugriffsrechte in Active Directory.
- **AFAS - Active Directory Kopplung:** Die HRM-Software von AFAS ermöglicht die Automatisierung sämtlicher HR-Prozesse für Personal- und Gehaltsverwaltung. Sie möchten jedoch auch, dass alle relevanten Informationen aus AFAS automatisch ihren Weg nach Active Directory finden. Dank der AFAS – Active Directory Kopplung, die HelloID ermöglicht, müssen Sie sich darum nicht kümmern.
- **SAP - Active Directory Kopplung:** SAP bietet im Rahmen von SAP Human Capital Management (HCM) verschiedene Lösungen, die HR bei den täglichen Aufgaben unterstützen. Wenn Sie SAP verwenden, möchten Sie sicherstellen, dass alle relevanten HR-Informationen automatisch in Active Directory verfügbar sind. Dank der SAP – Active Directory Kopplung haben Sie hierüber Gewissheit.

Mit Unterstützung für mehr als 200 Konnektoren ermöglicht HelloID eine breite Palette an Integrationen zwischen Active Directory und anderen Systemen. Um den sich ständig ändernden Anforderungen von Organisationen gerecht zu werden, erweitert Tools4ever das Angebot an Konnektoren und Integrationen kontinuierlich.
